_format_version: "1.1"
services:
- connect_timeout: 60000
  host: myservice-envoy
  name: myservice
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - hosts:
    - myservice.kongy.localhost
    id: 26bdb98b-0618-4291-a42c-fbdabf2a6f82
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
  plugins:
  - name: oidc
    config:
      access_token_as_bearer: "yes"
      access_token_header_name: Authorization
      bearer_jwt_auth_allowed_auds: null
      bearer_jwt_auth_enable: "no"
      bearer_jwt_auth_signing_algs:
      - RS256
      bearer_only: "no"
      client_id: myservice
      client_secret: 717f188a-d55f-403a-9069-d769701cc6ee
      disable_access_token_header: "no"
      disable_id_token_header: "no"
      disable_userinfo_header: "no"
      discovery: https://keycloak.localhost/auth/realms/master/.well-known/openid-configuration
      filters: null
      groups_claim: groups
      header_claims: []
      header_names: []
      id_token_header_name: X-ID-Token
      ignore_auth_filters: ""
      introspection_endpoint: https://keycloak.localhost/auth/realms/master/protocol/openid-connect/token/introspect
      introspection_endpoint_auth_method: null
      logout_path: /logout
      realm: kong
      recovery_page_path: null
      redirect_after_logout_uri: /
      redirect_uri: null
      response_type: code
      revoke_tokens_on_logout: "no"
      scope: openid
      session_secret: null
      skip_already_auth_requests: "no"
      ssl_verify: "no"
      timeout: null
      token_endpoint_auth_method: client_secret_post
      unauth_action: auth
      userinfo_header_name: X-USERINFO
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
