version: '3'

networks:
  default:
    external:
      name: keycloak-multigateway_default

services:
  petstore-envoy:
    build: ./compose/envoy
    volumes:
      - ./compose/envoy/envoy.yaml:/config/envoy.yaml
    environment:
      - DEBUG_LEVEL=debug
      - SERVICE_NAME=petstore
      - SERVICE_HOST=petstore-api
      - SERVICE_PORT=8080
      - OPA_HOST=petstore-opa

  petstore-opa:
    image: openpolicyagent/opa:0.25.2-envoy
    volumes:
      - ./compose/petstore/policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"

  petstore-api:
    image: openapitools/openapi-petstore
    environment:
      - OPENAPI_BASE_PATH=/v3
      - DISABLE_API_KEY=1
      - DISABLE_OAUTH=1

  myservice-envoy:
    build: ./compose/envoy
    volumes:
      - ./compose/envoy/envoy.yaml:/config/envoy.yaml
    environment:
      - DEBUG_LEVEL=info
      - SERVICE_NAME=myservice
      - SERVICE_HOST=myservice-api
      - SERVICE_PORT=80
      - OPA_HOST=myservice-opa

  myservice-opa:
    image: openpolicyagent/opa:0.25.2-envoy
    volumes:
      - ./compose/myservice/policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"

  myservice-api:
    build: ./compose/myservice
    volumes:
      - ./compose/myservice/app:/app
    entrypoint: /start-reload.sh
